name: Prevent merge on fridays

on:
    pull_request: 
        types: [opened, reopened, synchronize]

jobs:
    check_day_of_week:
        runs-on: ubuntu-22.04
        steps:
            - name: Check day of week
              id: check_day
              run: echo "DAY_OF_WEEK=$(date +'%A') >> $GITHUB_OUTPUT"
            - name: Fail if it`s a Friday
              if: steps.check_day.outputs.DAY_OF_WEEK == 'Friday'
              run: exit 1